### ISSUE TITLE
ClinVar variant included without any pathogenic/likely pathogenic in list of conflicts

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/genetic-prevalence-estimator#228]
There is a variant on this list that is being brought in from ClinVar  ([4-127921956-C-G](https://gnomad.broadinstitute.org/variant/4-127921956-C-G?dataset=gnomad_r4)), which is conflicting but one of the conflicts isn't pathogenic. 

https://genie.broadinstitute.org/variant-lists/79c87528-3269-4b0c-88c8-dbf74f3fc799/

---

- https://www.ncbi.nlm.nih.gov/clinvar/variation/162378/
- https://gnomad.broadinstitute.org/variant/4-127921956-C-G?dataset=gnomad_r4
- https://genie.broadinstitute.org/variant-lists/79c87528-3269-4b0c-88c8-dbf74f3fc799/

**Comment by rileyhgrant** [comment]
Hmm ok, so I believe the reason the variant in the original issue ([4-127921956-C-G](https://gnomad.broadinstitute.org/variant/4-127921956-C-G?dataset=gnomad_r4)) is included is because when this list was created, it either had a different classification in ClinVar, or the logic of GeniE was not correct.

When I create a new list for this gene (MFSD8) on v4.1 with ClinVar variants including P/LP and Conflicting, this variant does not show up at all in the generated list.

So I believe, this is an issue of needing to have the feature to remove variants from a list permanently (#124), and not an issue of GeniE's current logic.

I'm going to close this issue while I investigate the second variant listed in the comments, if that's a seperate problem I'll open a standalone issue for that.

**Comment by rileyhgrant** [comment]
I found the same for the second example ([genie.broadinstitute.org/variant-lists/b5a78bca-9ca0-4495-b15e-55461a9e05d3](https://genie.broadinstitute.org/variant-lists/b5a78bca-9ca0-4495-b15e-55461a9e05d3/) ([6-109785020-A-G](https://gnomad.broadinstitute.org/variant/6-109785020-A-G?dataset=gnomad_r4)))

When creating a new list, this variant is not included. So both these anomalies appear to be due to either incorrect older logic, or a change in the classifications on ClinVar. The best way to resolve these would likely be to allow tracking a secondary list of variants to never include in calculations.
