### ISSUE TITLE
ClinVar "Risk factors" should be removed from being brought in

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/genetic-prevalence-estimator#260]
In the pre-computed estimates we should remove "risk factor" or "	Conflicting classifications of pathogenicity, other, risk factor" or "benign" variants from being included

![image](https://github.com/broadinstitute/genetic-prevalence-estimator/assets/19212392/c9187dca-6f5c-46f3-967a-6fc22b25b602)

**Comment by sambaxter** [comment]
Had someone approach me about an "error" in one of the dashboard estimates and I think its related to this issue.  [This list](https://genie.broadinstitute.org/dashboard/ENSG00000143921)  has a benign missense variant being brought in and I can't figure out why
<img width="1120" alt="image" src="https://github.com/broadinstitute/genetic-prevalence-estimator/assets/19212392/0f846016-e993-40fb-8976-9a65595fafd3">

**Comment by rileyhgrant** [comment]
Agh, ok. It looks as though this particular variant has one pathogenic classification in ClinVar with 0 stars?

https://www.ncbi.nlm.nih.gov/clinvar/variation/4975/

For the purposes of handling conflicting cases to know whether or not to include ClinVar variants with conflicting interpretations, we keep this information around and use it when deciding whether or not to include a variant. This particular one being kept around because of that single 0 star submission, despite the listed classification of the variant being "Benign".

Will have to rethink this, this might be a good thing to discuss on Zoom at some point.
